language: node_js
node_js:
  - "node"
sudo: required
dist: trusty

notifications:
  email: false

addons:
  chrome: stable
cache:
  directories:
  - $HOME/.npm
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm i -g npm
  - npm ci
script:
  # run build script specified in package.json
  - npm run travis-ci
  # call script for deploying of produced artifacts
  # - bash ./.travis-deploy.sh
